spring.application.name=SkillBridge

spring.datasource.url=jdbc:postgresql://localhost:5432/skillbridge
spring.datasource.username=shivangiraj

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
